# Generated by Django 4.2.2 on 2023-06-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_room_type_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room',
            new_name='name',
        ),
    ]
