# Generated by Django 4.2.2 on 2023-06-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rename_end_time_booking_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_type',
            new_name='type',
        ),
    ]
